### ISSUE TITLE
Uploading the same file twice does not load binary

### ISSUE THREAD

**Issue by Alvinn8** [PumpedSardines/dtekv-emulator-web#3]
Try uploading main.bin, then recompile and upload main.bin again. Since the input element still has the "same" file selected, `onChange` doesn't trigger. Simply adding `e.currentTarget.value = "";` to clear the input should fix this.

**Comment by PumpedSardines** [comment]
I'll fix this right away

**Comment by PumpedSardines** [comment]
@Alvinn8 Are you sure this is a bug? I'm trying to recreate this locally but everything works as expected when doing exactly what is described in the issue
